### PR TITLE
Rearchitecting

### LINKED ISSUE #1: LGPL Compatible Licensing
@Danielku15, @jjxtra, @ToddBertaOldham
Continuation of [#12 in the old repository](https://github.com/ioctlLR/NVorbis/issues/12).

With the exception of Todd, all other submissions no longer apply as of the merge of the rearchitecting branch (the Ogg components, in particular, have been fully re-written), so given Todd's approval in the previous thread I'm going to re-license as MIT.

### PR DESCRIPTION
**Pull request by ioctlLR**
Huge re-write of ogg handling and refactoring of decoding logic.

Changes license to MIT.  Closes #1 

Thanks!

### CODE REVIEW

**Comment by ToddBertaOldham** [comment]
Nice work. I'll start looking through this soon. Also, on an unrelated note I'm in the process of changing my name so my GitHub account name will be different soon. Just so you know.

**Comment by ioctlLR** [comment]
Thanks, and sounds good.

File: NVorbis/Contracts/IContainerReader.cs [hunk 1]
```diff
@@ -0,0 +1,48 @@
...
+{
+    /// <summary>
+    /// Provides an interface for a Vorbis logical stream container.
+    /// </summary>
+    public interface IContainerReader : IDisposable
+    {
+        /// <summary>
+        /// Gets or sets the callback to invoke when a new stream is encountered in the container.
+        /// </summary>
+        Func<IPacketProvider, bool> NewStreamCallback { get; set; }
```
Comment (ToddBertaOldham) [inline NVorbis/Contracts/IContainerReader.cs]: This is a small thing but I noticed you had the delegate definition GetPacketGranuleCount in IPacketProvider. Any reason not to do that here or use Func instead of GetPacketGranuleCount?

File: NVorbis/Contracts/IStreamDecoder.cs [hunk 2]
```diff
@@ -0,0 +1,103 @@
...
+        /// Seeks the stream to the specified time.
+        /// </summary>
+        /// <param name="timePosition">The time to seek to.</param>
+        void SeekTo(TimeSpan timePosition);
+
+        /// <summary>
+        /// Seeks the stream to the specified sample.
+        /// </summary>
+        /// <param name="samplePosition">The sample position to seek to.</param>
+        void SeekTo(long samplePosition);
```
Comment (ToddBertaOldham) [inline NVorbis/Contracts/IStreamDecoder.cs]: Is there a difference between these two methods and just setting through properties? Do the properties not seek the underlying stream? Maybe add [SeekOrigin ](https://docs.microsoft.com/en-us/dotnet/api/system.io.seekorigin?view=netframework-4.8)for consistency with .Net?

File: NVorbis/Contracts/IVorbisReader.cs [hunk 3]
```diff
@@ -0,0 +1,142 @@
...
+        /// <returns>The number of samples read into the buffer.</returns>
+        /// <exception cref="ArgumentOutOfRangeException">Thrown when the buffer is too small or <paramref name="offset"/> is less than zero.</exception>
+        /// <remarks>The data populated into <paramref name="buffer"/> is interleaved by channel in normal PCM fashion: Left, Right, Left, Right, Left, Right</remarks>
+        int ReadSamples(float[] buffer, int offset, int count);
+
+        /// <summary>
+        /// Seeks the stream to the specified time.
+        /// </summary>
+        /// <param name="timePosition">The time to seek to.</param>
+        void SeekTo(TimeSpan timePosition);
```
Comment (ToddBertaOldham) [inline NVorbis/Contracts/IVorbisReader.cs]: Same as IStreamDecoder.

File: NVorbis/Contracts/ParameterChangeEventArgs.cs [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+        public ParameterChangeEventArgs(int channels, int sampleRate)
+        {
+            Channels = channels;
+            SampleRate = sampleRate;
+        }
+
+        /// <summary>
+        /// Get the new number of channels in the stream.
+        /// </summary>
+        public int Channels { get; private set; }
```
Comment (ToddBertaOldham) [inline NVorbis/Contracts/ParameterChangeEventArgs.cs]: Very small thing here. These two properties don't need private set.

File: NVorbis/DataPacket.cs [hunk 5]
```diff
@@ -37,50 +18,99 @@ protected enum PacketFlags : byte
...
+        /// </summary>
+        public int BitsRemaining => TotalBits - _readBits;
+
+        /// <summary>
+        /// Gets the total number of bits in the packet.
         /// </summary>
-        protected void SetFlag(PacketFlags flag, bool value)
+        abstract protected int TotalBits { get; }
+
+        bool GetFlag(PacketFlags flag) => (_packetFlags & flag) == flag;
```
Comment (ToddBertaOldham) [inline NVorbis/DataPacket.cs]: Isn't this just [HasFlag](https://docs.microsoft.com/en-us/dotnet/api/system.enum.hasflag?view=netframework-4.8)?

File: NVorbis/Contracts/IContainerReader.cs (hunk 1 above)
Comment (ioctlLR) [reply NVorbis/Contracts/IContainerReader.cs]: Good point.  I'll change this one to use a declared delegate instead.

File: NVorbis/Contracts/IStreamDecoder.cs (hunk 2 above)
Comment (ioctlLR) [reply NVorbis/Contracts/IStreamDecoder.cs]: Hmmm...  While that would technically be a breaking change, I think it's a good idea.  That also makes having the separate methods (which are currently identical to the property setters) "make sense".  I'll see about adding the parameter.

File: NVorbis/Contracts/IVorbisReader.cs (hunk 3 above)
Comment (ioctlLR) [reply NVorbis/Contracts/IVorbisReader.cs]: Ditto that. :)

File: NVorbis/Contracts/ParameterChangeEventArgs.cs (hunk 4 above)
Comment (ioctlLR) [reply NVorbis/Contracts/ParameterChangeEventArgs.cs]: It's the little things...  Will be fixed shortly.

File: NVorbis/DataPacket.cs (hunk 5 above)
Comment (ioctlLR) [reply NVorbis/DataPacket.cs]: Ha!  Good catch...  Probably not any faster, but is much cleaner.  Will be fixed shortly.

**Comment by ToddBertaOldham** [comment]
Great I'll keep going through the changes and let you know if I find anything else.

File: NVorbis/NewStreamEventArgs.cs [hunk 6]
```diff
@@ -16,20 +10,20 @@ namespace NVorbis
...
-        /// Creates a new instance of <see cref="NewStreamEventArgs"/> with the specified <see cref="IPacketProvider"/>.
+        /// Creates a new instance of <see cref="NewStreamEventArgs"/> with the specified <see cref="IStreamDecoder"/>.
         /// </summary>
-        /// <param name="packetProvider">An <see cref="IPacketProvider"/> instance.</param>
-        public NewStreamEventArgs(IPacketProvider packetProvider)
+        /// <param name="streamDecoder">An <see cref="IStreamDecoder"/> instance.</param>
+        public NewStreamEventArgs(IStreamDecoder streamDecoder)
         {
-            if (packetProvider == null) throw new ArgumentNullException("packetProvider");
+            if (streamDecoder == null) throw new ArgumentNullException("packetProvider");
```
Comment (ToddBertaOldham) [inline NVorbis/NewStreamEventArgs.cs]: The argument name in the exception needs to be updated. Some properties here can be made read only as well if you want but it's not a big deal.

File: NVorbis/VorbisReader.cs [hunk 7]
```diff
@@ -1,249 +1,282 @@
...
+        /// Cleans up this instance.
+        /// </summary>
         public void Dispose()
         {
             if (_decoders != null)
             {
                 foreach (var decoder in _decoders)
                 {
-                    decoder.Dispose();
+                    (decoder as IDisposable)?.Dispose();
```
Comment (ToddBertaOldham) [inline NVorbis/VorbisReader.cs]: What's the purpose of casting to IDisposable here? IStreamDecoder inherits from IDisposable right?

Comment (ioctlLR) [reply NVorbis/VorbisReader.cs]: At one point during development I'd removed IDisposable from the IStreamDecoder interface.  I later added it back in (I believe while working through the IPacketProvider lifetime handling).  It still works fine as-is, but for cleanliness I'll change it to call directly in the next push.

Comment (ToddBertaOldham) [reply NVorbis/VorbisReader.cs]: It's up to you. I don't want to waste your time with small cleanliness issues. Unless you want me to keep pointing this kind of stuff out, I was planning on stopping. ReSharper nags me about stuff like this all the time so it's easy for me to do the same. Also, sorry if this review is taking me a while. I've been busy with stuff, but I've gotten through most of the files.

Comment (ioctlLR) [reply NVorbis/VorbisReader.cs]: No worries.  You may notice I'm also not in any hurry to reply. :)

Do as much (or little) review as you feel is necessary.  I'm good with whatever you do there.

File: NVorbis/Ogg/ContainerReader.cs [hunk 8]
```diff
@@ -0,0 +1,154 @@
...
+
+        /// <summary>
+        /// Gets or sets the callback to invoke when a new stream is encountered in the container.
+        /// </summary>
+        public NewStreamHandler NewStreamCallback { get; set; }
+
+        /// <summary>
+        /// Gets a list of streams available from this container.
+        /// </summary>
+        public IReadOnlyList<Contracts.IPacketProvider> Streams
```
Comment (ToddBertaOldham) [inline NVorbis/Ogg/ContainerReader.cs]: This property would be much better as a method in my opinion since it allocates a new list every time. I don't know if anyone using the library will be using this class, but it is public.

File: TestApp/ForwardOnlyStream.cs [hunk 9]
```diff
@@ -0,0 +1,52 @@
+﻿using System;
+using System.IO;
+
+namespace TestApp
+{
+    class ForwardOnlyStream : Stream
```
Comment (ToddBertaOldham) [inline TestApp/ForwardOnlyStream.cs]: Any reason to include this file? It doesn't seem to be used at all. Out of curiosity why limit a stream like this?

File: NVorbis/Ogg/ContainerReader.cs (hunk 8 above)
Comment (ioctlLR) [reply NVorbis/Ogg/ContainerReader.cs]: Hmmm...  That's really an implementation detail, so I'm hesitant to change the public API there.  On the other hand, returning a new list every time is not a great idea...
What about a custom IReadOnlyList<IPacketProvider> implementation?  Use that instead of the List<WeakReference<IPacketProvider>> instance it uses now?

File: TestApp/ForwardOnlyStream.cs (hunk 9 above)
Comment (ioctlLR) [reply TestApp/ForwardOnlyStream.cs]: That's there so I can force use of the ForwardOnlyPageReader in ContainerReader.  I don't use it in the committed code, but do use it for testing.

File: NVorbis/Ogg/ContainerReader.cs (hunk 8 above)
Comment (ToddBertaOldham) [reply NVorbis/Ogg/ContainerReader.cs]: My main concern was that it being a property would hide the allocation. It would be easy to access the property multiple times when working with the list. A well named method would better communicate that you should just call it once and assign the created list to a variable. I'm not sure how often this property is accessed but this could probably be left alone and it wouldn't matter much at all even if someone misused the property. I was just going to suggest deprecating the property and saying to use the method instead.

Comment (ioctlLR) [reply NVorbis/Ogg/ContainerReader.cs:29]: Well, I looked at the possibility of implementing a WeakList<T> that implements IReadOnlyList<T>...  Nope, not in this release!  Too many corner cases and "gotchas" for this stage in the release cycle.  So I think I will change the public API to be a method.  Thanks for the suggestion.

File: NVorbis/NewStreamEventArgs.cs (hunk 6 above)
Comment (ioctlLR) [reply NVorbis/NewStreamEventArgs.cs:18]: I have this corrected in my local copy, so it'll be fixed when I push the last batch of changes here.

**Comment by ioctlLR** [comment]
Thanks for taking the time to really go over all this.  I think things are about as good as they can be for now, so I'll merge to master shortly and create a new release.

**Comment by ToddBertaOldham** [comment]
Sounds good. I'm still unfamiliar with the decoding process so hopefully I didn't miss anything major. As far as I can tell though everything looks great.
